<?php
echo "<ul>
<li>abu
    <ul>
        <li>
            Hassan
            <ul>
                <li>ali
                <ul>
                    <li>arif</li>
                    <li>taifuk</li>
                </ul>
                </li>
            <li>bakar</li>
            </ul>
        </li>
            <li>
                shahir
                <ul>
                    <li>hafiz</li>
                     <li>
                        afiq
                        <ul>
                            <li>muhd
                        <ul>
                    <li>sukor</li>
                </ul>
            </li>
        </ul>
        </li>
        </ul>
        </li>
        </li>
        </li>
    </ul>
</li>
</ul>";
?>

